# Generated by Django 3.2 on 2021-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('_pin', models.IntegerField(db_column='pin', default=0)),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='check',
            old_name='other_symptoms',
            new_name='_other_symptoms',
        ),
        migrations.AlterField(
            model_name='check',
            name='_other_symptoms',
            field=models.IntegerField(db_column='other_symptoms', default=0),
        ),
    ]
