# Generated by Django 3.2 on 2021-05-07 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidcheck', '0002_auto_20210508_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 22, 45, 34, 798091, tzinfo=utc), verbose_name='date_published'),
            preserve_default=False,
        ),
    ]
