# Generated by Django 3.2 on 2021-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidcheck', '0004_check_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='phone',
            field=models.BigIntegerField(verbose_name='phone_number'),
        ),
    ]
